In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
ti=pd.read_csv('Titanic')
ti.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [4]:
ti.shape

(891, 11)

In [5]:
ti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.6+ KB


In [6]:
ti.drop(['Name','Ticket','PassengerId'],axis=1,inplace=True)

In [7]:
ti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    891 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [9]:
ti['Sex']=le.fit_transform(ti['Sex'])

In [10]:
status= pd.get_dummies(ti['Embarked'],drop_first=True)

In [11]:
status.head()

Q  S
0  0  1
1  0  0
2  0  1
3  0  1
4  0  1

In [12]:
ti=pd.concat([ti,status],axis=1)
ti.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked  Q  S
0         0       3    1  22.0      1      0   7.2500        S  0  1
1         1       1    0  38.0      1      0  71.2833        C  0  0
2         1       3    0  26.0      0      0   7.9250        S  0  1
3         1       1    0  35.0      1      0  53.1000        S  0  1
4         0       3    1  35.0      0      0   8.0500        S  0  1

In [13]:
ti.drop('Embarked',axis=1,inplace=True)

In [14]:
ti.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Q  S
0         0       3    1  22.0      1      0   7.2500  0  1
1         1       1    0  38.0      1      0  71.2833  0  0
2         1       3    0  26.0      0      0   7.9250  0  1
3         1       1    0  35.0      1      0  53.1000  0  1
4         0       3    1  35.0      0      0   8.0500  0  1

In [15]:
# fig=plt.figure()
# sns.heatmap(ti.corr(),annot=True,ax=fig.add_axes([0,0,2,2]))

In [16]:
ti.shape

(891, 9)

In [17]:
ti.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Q', 'S'], dtype='object')

In [18]:
ti[['Age','Fare']].describe(percentiles=[0.015,0.25,0.5,0.75,0.98,0.997])

Age        Fare
count  891.000000  891.000000
mean    23.978075   32.204208
std     17.356023   49.693429
min      0.420000    0.000000
1.5%     0.899973    0.000000
25%      6.000000    7.910400
50%     24.000000   14.454200
75%     35.000000   31.000000
98%     62.000000  211.337500
99.7%   71.000000  345.278636
max     80.000000  512.329200

In [19]:
ti=ti[ti['Age']<=71]

In [20]:
# ti=ti[ti['Fare']<=345]
ti=ti[ti['Fare']<=211]

In [21]:
ti.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Q  S
0         0       3    1  22.0      1      0   7.2500  0  1
1         1       1    0  38.0      1      0  71.2833  0  0
2         1       3    0  26.0      0      0   7.9250  0  1
3         1       1    0  35.0      1      0  53.1000  0  1
4         0       3    1  35.0      0      0   8.0500  0  1

In [22]:
x=ti.drop('Survived',axis=1)
y=ti.Survived

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=101)

In [24]:
from sklearn.preprocessing import StandardScaler
# x_train=x_train[x_train['Fare']<1]
sc=StandardScaler()
x_train[['Age','Fare']]=sc.fit_transform(x_train[['Age','Fare']])
x_train_scaled=x_train

In [25]:
x_train_scaled.head()

Pclass  Sex       Age  SibSp  Parch      Fare  Q  S
65        3    1 -1.374223      1      1 -0.394715  0  0
619       2    1  0.102264      0      0 -0.555590  0  1
278       3    1 -1.015394      4      1  0.075765  1  0
191       2    1 -0.309505      0      0 -0.470844  0  1
30        1    1  0.925802      0      0  0.028165  0  0

In [26]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()

In [27]:
from sklearn.feature_selection import RFE
rfe=RFE(lgr,6)
rfe=rfe.fit(x_train_scaled,y_train)

In [28]:
list(zip(x_train_scaled,rfe.support_,rfe.ranking_))

[('Pclass', True, 1),
 ('Sex', True, 1),
 ('Age', True, 1),
 ('SibSp', True, 1),
 ('Parch', False, 2),
 ('Fare', True, 1),
 ('Q', False, 3),
 ('S', True, 1)]

In [29]:
sel_col=x_train_scaled.columns[rfe.support_]

In [30]:
x_train_scaled_rfe=x_train_scaled[sel_col]
x_train_scaled_rfe.head()

Pclass  Sex       Age  SibSp      Fare  S
65        3    1 -1.374223      1 -0.394715  0
619       2    1  0.102264      0 -0.555590  1
278       3    1 -1.015394      4  0.075765  0
191       2    1 -0.309505      0 -0.470844  1
30        1    1  0.925802      0  0.028165  0

In [31]:
lgr.fit(x_train_scaled_rfe,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
y_pred_lgr_train=lgr.predict(x_train_scaled_rfe)

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [34]:
print('Accurecy : ',accuracy_score(y_train,y_pred_lgr_train))

Accurecy :  0.819078947368421


In [35]:
print('Confusion :\n\n',confusion_matrix(y_train,y_pred_lgr_train))

Confusion :

 [[329  44]
 [ 66 169]]


In [36]:
x_test[['Age','Fare']]=sc.transform(x_test[['Age','Fare']])

In [37]:
x_test_rfe=x_test[x_train_scaled_rfe.columns]

In [38]:
y_pred_lgr_test=lgr.predict(x_test_rfe)

In [39]:
print('Accuresy: ',accuracy_score(y_test,y_pred_lgr_test))

Accuresy:  0.7586206896551724


In [40]:
print("Confussion Matrix:\n\n",confusion_matrix(y_test,y_pred_lgr_test))

Confussion Matrix:

 [[142  27]
 [ 36  56]]


## Finding Accurecy  for training using StatsModel

In [41]:
import statsmodels.api as sm

In [42]:
x_train_scaled_rfe_sm=sm.add_constant(x_train_scaled_rfe)

In [59]:
x_train_scaled_rfe_sm.head()

const  Pclass  Sex       Age  SibSp      Fare  S
65     1.0       3    1 -1.374223      1 -0.394715  0
619    1.0       2    1  0.102264      0 -0.555590  1
278    1.0       3    1 -1.015394      4  0.075765  0
191    1.0       2    1 -0.309505      0 -0.470844  1
30     1.0       1    1  0.925802      0  0.028165  0

In [44]:
logm=sm.GLM(y_train,x_train_scaled_rfe_sm,family=sm.families.Binomial()).fit()

In [45]:
logm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:               Survived   No. Observations:                  608
Model:                            GLM   Df Residuals:                      601
Model Family:                Binomial   Df Model:                            6
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -263.52
Date:                Thu, 12 Sep 2019   Deviance:                       527.04
Time:                        11:58:24   Pearson chi2:                     640.
No. Iterations:                     5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.4049      0.538      8.193      0.000       3.351       5.459
Pclass        -1.1849      0.196     -6.035      0.000      -1.570      -0.800
Sex           -2.7263      0.239    -11.422      0.000      -3.194      -2.258
Age           -0.3796      0.123     -3.090      0.002      -0.620      -0.139
SibSp         -0.3720      0.139     -2.683      0.007      -0.644      -0.100
Fare           0.1377      0.173      0.794      0.427      -0.202       0.478
S             -0.4825      0.249     -1.937      0.053      -0.971       0.006
==============================================================================
"""

In [46]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif=pd.DataFrame()
vif['Features']=x_train_scaled_rfe_sm.columns
vif['VIF']=[variance_inflation_factor(x_train_scaled_rfe_sm.values,i) for i in range(x_train_scaled_rfe_sm.shape[1])]
vif['VIF']=round(vif['VIF'],2)
vif=vif.sort_values(by='VIF',ascending=False)
vif

Features    VIF
0    const  22.08
1   Pclass   2.21
5     Fare   2.20
3      Age   1.28
4    SibSp   1.28
6        S   1.08
2      Sex   1.07

In [48]:
lgr()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [50]:
y_train_pred_sm=logm.predict(x_train_scaled_rfe_sm)

In [51]:
# round(y_train_pred_sm,2)

In [52]:
print('Accuracy Score:\n')
print(accuracy_score(y_train,y_train_pred_sm.round()),'\n')
print('confution:\n')
print(confusion_matrix(y_train,y_train_pred_sm.round()))

Accuracy Score:

0.8157894736842105 

confution:

[[324  49]
 [ 63 172]]


In [ ]:
print('Classification :',classification_report(y_test,y_test_pred_sm.round()))

## Finding Accuracy for test using Statsmodel

In [53]:
x_test_scaled_rfe_sm=sm.add_constant(x_test_rfe)
x_test_scaled_rfe_sm.head()

const  Pclass  Sex       Age  SibSp      Fare  S
722    1.0       2    1  0.572857      0 -0.470844  1
655    1.0       2    1 -0.015384      2  1.580001  1
175    1.0       3    1 -0.368329      1 -0.645278  1
234    1.0       2    1 -0.015384      0 -0.555590  1
126    1.0       3    1 -1.374223      0 -0.648810  0

In [54]:
logm1=sm.GLM(y_test,x_test_rfe,family=sm.families.Binomial()).fit()

In [55]:
logm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:               Survived   No. Observations:                  261
Model:                            GLM   Df Residuals:                      255
Model Family:                Binomial   Df Model:                            5
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -129.67
Date:                Thu, 12 Sep 2019   Deviance:                       259.34
Time:                        11:58:42   Pearson chi2:                     259.
No. Iterations:                     5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass         0.2111      0.142      1.489      0.137      -0.067       0.489
Sex           -2.2210      0.323     -6.881      0.000      -2.854      -1.588
Age           -0.2342      0.165     -1.420      0.156      -0.557       0.089
SibSp         -0.3318      0.173     -1.919      0.055      -0.671       0.007
Fare           0.7907      0.207      3.812      0.000       0.384       1.197
S              0.5079      0.351      1.447      0.148      -0.180       1.196
==============================================================================
"""

In [56]:
vif=pd.DataFrame()
vif['Features']=x_test_scaled_rfe_sm.columns
vif['VIF']=[variance_inflation_factor(x_test_scaled_rfe_sm.values,i) for i in range(x_test_scaled_rfe_sm.shape[1])]
vif['VIF']=round(vif['VIF'],2)
vif=vif.sort_values(by='VIF',ascending=False)
vif

Features    VIF
0    const  21.91
5     Fare   2.18
1   Pclass   2.07
4    SibSp   1.26
3      Age   1.17
2      Sex   1.11
6        S   1.07

In [61]:
y_test_pred_sm=logm1.predict(x_test_rfe)

In [62]:
print('Accuracy Score:\n')
print(accuracy_score(y_test,y_test_pred_sm.round()),'\n')
print('confution: \n')
print(confusion_matrix(y_test,y_test_pred_sm.round()))

Accuracy Score:

0.7816091954022989 

confution: 

[[146  23]
 [ 34  58]]


In [64]:
print('Classification :',classification_report(y_test,y_test_pred_sm.round()))

Classification :               precision    recall  f1-score   support

           0       0.81      0.86      0.84       169
           1       0.72      0.63      0.67        92

    accuracy                           0.78       261
   macro avg       0.76      0.75      0.75       261
weighted avg       0.78      0.78      0.78       261

