In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats as s

In [3]:
ba=pd.read_csv('bank-full.csv',sep=';')
ba.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [4]:
ba.isnull().sum().sum()

0

In [5]:
ba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
age          45211 non-null int64
job          45211 non-null object
marital      45211 non-null object
education    45211 non-null object
default      45211 non-null object
balance      45211 non-null int64
housing      45211 non-null object
loan         45211 non-null object
contact      45211 non-null object
day          45211 non-null int64
month        45211 non-null object
duration     45211 non-null int64
campaign     45211 non-null int64
pdays        45211 non-null int64
previous     45211 non-null int64
poutcome     45211 non-null object
y            45211 non-null object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [6]:
ba.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [7]:
ba.drop(['duration','contact'],axis=1,inplace=True)

In [8]:
# x=ba.drop('y',axis=1)

In [9]:
# x=pd.get_dummies(x,drop_first=True)

In [10]:
# x.shape

In [11]:
# x.skew()

In [12]:
# x[np.abs(s.zscore(x['balance']))>3].count()

In [13]:
ba1=ba[(ba['balance']<=1500) & (ba['balance']>=0)]

In [14]:
ba_outlier1=ba[ba['balance']>1500]

In [15]:
ba_outlier2=ba[ba['balance']<0]

In [16]:
print(ba1.shape)
print(ba_outlier1.shape)
print(ba_outlier2.shape)

(30550, 15)
(10895, 15)
(3766, 15)


In [17]:
ba1.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'day', 'month', 'campaign', 'pdays', 'previous', 'poutcome',
       'y'],
      dtype='object')

In [18]:
ba1['new_cust']=ba1['previous'].apply(lambda row:1 if (row==0) else 0)

In [19]:
ba1['new_cust'].value_counts()

1    25130
0     5420
Name: new_cust, dtype: int64

In [20]:
ba1.drop('previous',axis=1,inplace=True)

In [21]:
ba1.drop('pdays',axis=1,inplace=True)

In [22]:
ba1.shape

(30550, 14)

In [23]:
ba1=pd.get_dummies(ba1,drop_first=True)

In [24]:
ba1.columns

Index(['age', 'balance', 'day', 'campaign', 'new_cust', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student', 'job_technician',
       'job_unemployed', 'job_unknown', 'marital_married', 'marital_single',
       'education_secondary', 'education_tertiary', 'education_unknown',
       'default_yes', 'housing_yes', 'loan_yes', 'month_aug', 'month_dec',
       'month_feb', 'month_jan', 'month_jul', 'month_jun', 'month_mar',
       'month_may', 'month_nov', 'month_oct', 'month_sep', 'poutcome_other',
       'poutcome_success', 'poutcome_unknown', 'y_yes'],
      dtype='object')

In [25]:
ba1.shape

(30550, 39)

In [26]:
x=ba1.drop('y_yes',axis=1)
y=ba1.y_yes

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
sc=StandardScaler()

In [31]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

In [32]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()

In [33]:
x_lgr=lgr.fit(x_train_sc,y_train)

In [34]:
y_pred=lgr.predict(x_train_sc)

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [36]:
accuracy_score(y_train,y_pred)

0.9026420388122516

In [37]:
y_pred1=lgr.predict(x_test_sc)

In [38]:
accuracy_score(y_test,y_pred1)

0.9006001091107474

In [39]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.91      0.99      0.95      8178
           1       0.64      0.18      0.28       987

    accuracy                           0.90      9165
   macro avg       0.77      0.58      0.61      9165
weighted avg       0.88      0.90      0.87      9165



## For Outliers

In [40]:
ba_outlier1['new_cust']=ba_outlier1['previous'].apply(lambda row:1 if (row==0) else 0)

In [41]:
ba_outlier1['new_cust'].value_counts()

1    8546
0    2349
Name: new_cust, dtype: int64

In [42]:
ba_outlier1.drop(['previous','pdays'],axis=1,inplace=True)

In [43]:
ba_outlier1.shape

(10895, 14)

In [44]:
ba_outlier1=pd.get_dummies(ba_outlier1,drop_first=True)

In [45]:
ba_outlier1.columns

Index(['age', 'balance', 'day', 'campaign', 'new_cust', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student', 'job_technician',
       'job_unemployed', 'job_unknown', 'marital_married', 'marital_single',
       'education_secondary', 'education_tertiary', 'education_unknown',
       'default_yes', 'housing_yes', 'loan_yes', 'month_aug', 'month_dec',
       'month_feb', 'month_jan', 'month_jul', 'month_jun', 'month_mar',
       'month_may', 'month_nov', 'month_oct', 'month_sep', 'poutcome_other',
       'poutcome_success', 'poutcome_unknown', 'y_yes'],
      dtype='object')

In [46]:
x1=ba_outlier1.drop('y_yes',1)
y1=ba_outlier1.y_yes

In [47]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.3,random_state=42)

In [48]:
x1_train_sc=sc.fit_transform(x1_train)
x1_test_sc=sc.transform(x1_test)

In [49]:
x1_lgr=lgr.fit(x1_train_sc,y1_train)

In [50]:
y_pred2=lgr.predict(x1_train_sc)

In [51]:
accuracy_score(y1_train,y_pred2)

0.8432992394440073

In [52]:
y_pred3=lgr.predict(x1_test_sc)

In [53]:
accuracy_score(y1_test,y_pred3)

0.8605078005506271

In [54]:
print(classification_report(y1_test,y_pred3))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      2763
           1       0.63      0.24      0.35       506

    accuracy                           0.86      3269
   macro avg       0.75      0.61      0.64      3269
weighted avg       0.84      0.86      0.83      3269



In [55]:
from sklearn.decomposition import PCA

In [56]:
pca=PCA(n_components=10)

In [57]:
x_train_pca=pca.fit_transform(x_train_sc)
x_test_pca=pca.transform(x_test_sc)

In [58]:
lgr1=LogisticRegression()

In [59]:
x_lgr1=lgr1.fit(x_train_pca,y_train)

In [60]:
y_pred_pca=lgr1.predict(x_train_pca)

In [61]:
accuracy_score(y_train,y_pred_pca)

0.8968903436988543

In [62]:
y_pred1_pca=lgr1.predict(x_test_pca)

In [63]:
accuracy_score(y_test,y_pred1_pca)

0.8974358974358975

In [64]:
print(classification_report(y_test,y_pred1_pca))

              precision    recall  f1-score   support

           0       0.90      0.99      0.95      8178
           1       0.62      0.12      0.20       987

    accuracy                           0.90      9165
   macro avg       0.76      0.56      0.57      9165
weighted avg       0.87      0.90      0.87      9165



## For Real data

In [65]:
bank=pd.read_csv('bank-full.csv',sep=';')
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [66]:
bank=pd.get_dummies(bank,drop_first=True)

In [67]:
x2=bank.drop('y_yes',1)
y2=bank.y_yes

In [68]:
x2_train,x2_test,y2_train,y2_test=train_test_split(x2,y2,test_size=0.3,random_state=42)

In [69]:
x2_train_sc=sc.fit_transform(x2_train)
x2_test_sc=sc.transform(x2_test)

In [70]:
lg=LogisticRegression()

In [71]:
x_lg=lg.fit(x2_train_sc,y2_train)

In [72]:
y_lg_p=lg.predict(x2_train_sc)

In [73]:
accuracy_score(y2_train,y_lg_p)

0.9030555818876986

In [74]:
print(classification_report(y2_train,y_lg_p))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95     27956
           1       0.66      0.35      0.46      3691

    accuracy                           0.90     31647
   macro avg       0.79      0.66      0.70     31647
weighted avg       0.89      0.90      0.89     31647



In [75]:
y_lg1_p=lg.predict(x2_test_sc)

In [76]:
accuracy_score(y2_test,y_lg1_p)

0.899955765260985

In [77]:
print(classification_report(y2_test,y_lg1_p))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94     11966
           1       0.64      0.34      0.45      1598

    accuracy                           0.90     13564
   macro avg       0.78      0.66      0.70     13564
weighted avg       0.88      0.90      0.89     13564



In [78]:
pca=PCA(n_components=10)

In [79]:
x2_train_pca=pca.fit_transform(x2_train_sc)
x2_test_pca=pca.transform(x2_test_sc)

In [80]:
lg.fit(x2_train_pca,y2_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [81]:
y_lg_p2=lg.predict(x2_train_pca)

In [82]:
accuracy_score(y2_train,y_lg_p2)

0.8876038803046102

In [83]:
y_lg_p3=lg.predict(x2_test_pca)

In [84]:
accuracy_score(y2_test,y_lg_p3)

0.8860218224712474

In [85]:
print(classification_report(y2_test,y_lg_p3))

              precision    recall  f1-score   support

           0       0.89      0.99      0.94     11966
           1       0.59      0.11      0.19      1598

    accuracy                           0.89     13564
   macro avg       0.74      0.55      0.56     13564
weighted avg       0.86      0.89      0.85     13564



In [93]:
col=[]
for c in list(ba.columns):
    if len(set(ba[c]))<13:
        print(c)
        col.append(c)

job
marital
education
default
housing
loan
month
poutcome
y


In [95]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for co in col:
    ba[co]=le.fit_transform(ba[co])

In [96]:
ba.head()

age  job  marital  education  default  balance  housing  loan  day  month  \
0   58    4        1          2        0     2143        1     0    5      8   
1   44    9        2          1        0       29        1     0    5      8   
2   33    2        1          1        0        2        1     1    5      8   
3   47    1        1          3        0     1506        1     0    5      8   
4   33   11        2          3        0        1        0     0    5      8   

   campaign  pdays  previous  poutcome  y  
0         1     -1         0         3  0  
1         1     -1         0         3  0  
2         1     -1         0         3  0  
3         1     -1         0         3  0  
4         1     -1         0         3  0

In [98]:
ba.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
day          0
month        0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [99]:
rfc_x=ba.drop(['age','y'],1)
rfc_y=ba['y']

In [108]:
rfc_x_train,rfc_x_test,rfc_y_train,rfc_y_test=train_test_split(x,y,test_size=0.3,random_state=42)

## Random classifier

In [109]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [110]:
rfc.fit(rfc_x_train,rfc_y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [111]:
rfc_pred=rfc.predict(rfc_x_train)

In [112]:
print(accuracy_score(rfc_y_train,rfc_pred))
print()
print(confusion_matrix(rfc_y_train,rfc_pred))
print()
print(classification_report(rfc_y_train,rfc_pred))

0.9850362403553893

[[19067     4]
 [  316  1998]]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     19071
           1       1.00      0.86      0.93      2314

    accuracy                           0.99     21385
   macro avg       0.99      0.93      0.96     21385
weighted avg       0.99      0.99      0.98     21385



In [113]:
rfc_pred2=rfc.predict(rfc_x_test)

In [114]:
print(accuracy_score(rfc_y_test,rfc_pred2))
print()
print(confusion_matrix(rfc_y_test,rfc_pred2))
print()
print(classification_report(rfc_y_test,rfc_pred2))

0.8963447899618112

[[8039  139]
 [ 811  176]]

              precision    recall  f1-score   support

           0       0.91      0.98      0.94      8178
           1       0.56      0.18      0.27       987

    accuracy                           0.90      9165
   macro avg       0.73      0.58      0.61      9165
weighted avg       0.87      0.90      0.87      9165



## Xgboost

In [117]:
import xgboost
from xgboost import XGBClassifier
xgb=XGBClassifier()

In [120]:
xgb.fit(rfc_x_train,rfc_y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [121]:
xgb_pred=xgb.predict(rfc_x_train)

In [122]:
print(accuracy_score(rfc_y_train,xgb_pred))
print()
print(confusion_matrix(rfc_y_train,xgb_pred))
print()
print(classification_report(rfc_y_train,xgb_pred))

0.9056347907411737

[[18885   186]
 [ 1832   482]]

              precision    recall  f1-score   support

           0       0.91      0.99      0.95     19071
           1       0.72      0.21      0.32      2314

    accuracy                           0.91     21385
   macro avg       0.82      0.60      0.64     21385
weighted avg       0.89      0.91      0.88     21385



In [123]:
xgb_pred2=xgb.predict(rfc_x_test)

In [124]:
print(accuracy_score(rfc_y_test,xgb_pred2))
print()
print(confusion_matrix(rfc_y_test,xgb_pred2))
print()
print(classification_report(rfc_y_test,xgb_pred2))

0.9018003273322422

[[8083   95]
 [ 805  182]]

              precision    recall  f1-score   support

           0       0.91      0.99      0.95      8178
           1       0.66      0.18      0.29       987

    accuracy                           0.90      9165
   macro avg       0.78      0.59      0.62      9165
weighted avg       0.88      0.90      0.88      9165



## Adaboost

In [125]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier()

In [126]:
ada.fit(rfc_x_train,rfc_y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [127]:
ada_pred=ada.predict(rfc_x_train)

In [128]:
print(accuracy_score(rfc_y_train,ada_pred))
print()
print(confusion_matrix(rfc_y_train,ada_pred))
print()
print(classification_report(rfc_y_train,ada_pred))

0.9005377601122282

[[18816   255]
 [ 1872   442]]

              precision    recall  f1-score   support

           0       0.91      0.99      0.95     19071
           1       0.63      0.19      0.29      2314

    accuracy                           0.90     21385
   macro avg       0.77      0.59      0.62     21385
weighted avg       0.88      0.90      0.88     21385



In [129]:
ada_pred2=ada.predict(rfc_x_test)

In [130]:
print(accuracy_score(rfc_y_test,ada_pred2))
print()
print(confusion_matrix(rfc_y_test,ada_pred2))
print()
print(classification_report(rfc_y_test,ada_pred2))

0.898417894162575

[[8052  126]
 [ 805  182]]

              precision    recall  f1-score   support

           0       0.91      0.98      0.95      8178
           1       0.59      0.18      0.28       987

    accuracy                           0.90      9165
   macro avg       0.75      0.58      0.61      9165
weighted avg       0.87      0.90      0.87      9165

